fixed_cost = float(input("Fixed Cost:"))
cost_per_unit = float(input("Cost per Unit:"))
price_per_unit = float(input("Price per Unit:"))
break_even_units = fixed_cost / (price_per_unit - cost_per_unit)
print(break_even_units)